### ISSUE TITLE
Year /  Month selection in datepicker

### ISSUE THREAD

**Issue by ksambhav** [lumapps/lumX#126]
http://ui.lumapps.com/directives/date-picker

I believe there should be a way to directly navigate to a given year/month. As per current design, one has to click though all months to change year in date.

This seems inconvenient while choose DOB for example.

**Comment by malexandre** [comment]
It's in progress. @nishith29 asked me what he could do on this components and we talk about it. The ergonomics we chose is exactly the same as the Android's one. When you click on the year, you get a "year picker" instead of a "day picker". For the month selection, it will stay as it is. But once we can change the year easily, the month doesn't need more work.

**Comment by matmkian** [comment]
We now provide a year selector, exactly as described in Material Design Guidelines.

**Comment by nishith29** [comment]
Ok. Does my code support your requirements? Tell me the next roadmap for
other elements. I really want to contribute at maximum
