### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by michalmw** [lumapps/lumX#130]
Hello,
I have problem in lumx. 
When i download lumx on my localhost and launch 'index.html' i have blank page. I must install somethink on my localhost? I try read somethink about this but i can't find.. 

Someone can help me ;)?
I have newbide front-end programmer and try learning this framework.

**Comment by malexandre** [comment]
Hi!
The index.html is made to be used with an AppEngine server because we manage some routing with it.  You can start it by following the steps in the [Running documentation locally](https://github.com/lumapps/lumX#running-documentation-locally). I might take the time in the future to manage this without AppEngine, but not for now. And if you just want to use it on your project, you don't need to use the included demo.

**Comment by michalmw** [comment]
Hello,
thx for you answer :). You very helpfull. 

You know demo project (1 page, form or somethink) when i dont; need AppEngine and can start use on localhost without install Google AppEngine?

Thx!

**Comment by malexandre** [comment]
I don't have an ETA, sorry.

**Comment by matmkian** [comment]
Hi, you can now run the project with any server you like. By running gulp task, all needed files will be builded in the build folder.
