### ISSUE TITLE
Search filter not working

### ISSUE THREAD

**Issue by alihalabyah** [lumapps/lumX#221]
The search filter won't copy the model attribute to the generated text input which result in a text box not connected with `ng-repeat` for example.

**Comment by malexandre** [comment]
Hi!

I'm not sur that I understand, si I'll try to describe your problem, please confirm that I understood:
 1- You use the search filter. If you type something, everything's good.
 2- If you modify the model attribute from your controller, it won't refresh the search filter display.

And if it's really this, can you please post the code sample from your project on how you use the search filter? I'll check the search filter code for now. Thanks!

**Comment by alihalabyah** [comment]
Sorry @malexandre I wrote this on quick and did not expect that fast response :)

So basically I'm trying to use the search filter with the `ng-repeat` as described here: https://docs.angularjs.org/api/ng/filter/filter

The problem is that whenever i try to use the `lx-search-filter` the directive itself does not copy the model attribute to the text box it generates instead it gives the `ng-model` the value `model` which will end up with a broken search filter.

Btw!, I tried to use a native input `<input ng-model="search">` and it worked!

**Comment by malexandre** [comment]
Can you paste a concrete example? I just updated the u plunkr you linked to work with lumx's search filter, and it works well: http://plnkr.co/edit/lQFfELvlFOmjH0F4G9TZ?p=preview

But I don't like this example. In Angular, and it was said by the Angular team themselves:
"If you use ng-model there has to be a dot somewhere. If you don't have a dot, you're doing it wrong."

In summary, you need the dot because of the scope inheritance, and our directives have their own scopes. So you should always have a dot.

**Comment by alihalabyah** [comment]
@malexandre thank you for the clarification and the advice, now i can see it working :) but i have no idea what was going on heheh, anyway I appreciate your very fast response!
