### ISSUE TITLE
frustrating documentation

### ISSUE THREAD

**Issue by jmls** [lumapps/lumX#237]
one area I find lumx to be extremely lacking is in the documentation :(

where can I find docs about the textarea directive ? I want to set the number of rows ..

Also, how can I make a column fit the viewport (ie take up all the vertical space)

Is there a google group list, or mailing list for lumx ?

thanks

**Comment by dhawken** [comment]
+1

**Comment by jmls** [comment]
anyone ?

**Comment by matmkian** [comment]
Hi, we're sorry for the lack of support these days...
We have a lot of work but we're going to have some times to work on LumX again next week :-)

**Comment by jmijmi** [comment]
Glad to hear, thank you for your contributions :)

**Comment by malexandre** [comment]
I'll try to make some blog post on what we're working on (like the documentation!), and we'll see what means of communication we'll use for everyone to now what's happening and to maybe talk more easily than in a github issue. But we now the documentation needs lot of works, with more and more example. It's coming!

**Comment by matmkian** [comment]
We're working on this enhancement. Soon a new release of LumX with real documentation and major enhancements. Keep an eye on https://twitter.com/lumapps.

**Comment by vanilla-thunder** [comment]
one year later: documentation is still outdated and incomplete

![shame](http://www.relatably.com/m/img/shame-memes/image.png)

many documentation pages say "This component has been completly reworked since LumX beta version (v0.3.96). Please refer to the updated documentation." But where is this updated documentation?

I like lumx very much, but bc breaks and lack of documentation scare many developers away
