### ISSUE TITLE
Increase of the contrast of form elements

### ISSUE THREAD

**Issue by digitalcraftsman** [lumapps/lumX#244]
Would it be possible to set the default font-weight higher or increase alternatively the font-size for [form elements](http://ui.lumapps.com/directives/text-fields)?

The light grey font-color is not very readable, especially with a white background.

**Comment by malexandre** [comment]
Hi!

I'll see with @matmkian, but I think it could be done with custom value in your sass, exactly like the customization of the colors. But I'm not sure because the typography is well defined by the MD spec, so this settings might not be changed like that.

But this won't be change directly on LumX exactly because of that, we're only following the specifications. And we think it looks great as is. Are you on Linux ? I know some fonts looks really thin (too much) there. I'm on Linux and I had to install some package and custom fonts for Helvetica for example.

**Comment by digitalcraftsman** [comment]
I'll work with custom values in sass. Currently I'm working on Windows 8 and didn't recognized such issues. But my contrast issue should be solved this way.
