### ISSUE TITLE
Select component - slow responsivness after multiple opens

### ISSUE THREAD

**Issue by deel77** [lumapps/lumX#256]
I am having problem with select component. When I have a more choices and open it repeatedly everything slows down. It also happends with small number of choices but after much more select openings.

It looks like it is creating always new elements with every opening of dropdown or something like that.
You can test it here: http://plnkr.co/edit/zLDp0qUVA6oCusOKVnSF?p=preview
just try responsivness by typing into input field after opening select (dropdown) at least 5 times (every opening of dropdown slows it more and more)

I am not sure what is the problem, I just have found out that `isChoicesVisible()` is called increasing number of times after each opening of select component, but I don't think this is the main source of problem.

Its really bad for my app right now. Can you help, or can I help with something about it?

**Comment by Argetloum** [comment]
Hi,
You can try to use angular filter for your list of items, like this:

            function filterAllItems(newValue, oldValue)
            {
                myServiceFilteredList = $filter('filter')(allItems, {'name': newValue}).splice(0, 10);
            }

Then add the filter option in your lxSelect, like this: 

            filter="myService.filterAllItems(newValue, oldValue)"

**Comment by matmkian** [comment]
Hi,

We heave the same problem on our app and it's a big issue.
We're going to work on it very very soon, maybe this week.

**Comment by deel77** [comment]
@Argetloum thanks, but this does not solve the problem only pospone it to later... still not bad, but I would love some different solution as it is vital for me to use at least 20 visible items for some usecases

**Comment by Argetloum** [comment]
@deel77 of course. 
Like @matmkian said, we will work on a different solution to improve performances.

**Comment by coty-crg** [comment]
+1 - I tried using select on a list of 1,000 entires. After opening the select box the whole page is super sluggish on my machine. My work around for now is to make it fetch a list from a server as you type in a query.. but it's not a permanent solution. Really needs to be looked into on lumx's side.

**Comment by malexandre** [comment]
One of my priority! I'll get back as soon as I have something.

**Comment by malexandre** [comment]
I finally found time to work on this. I made multiple enhancements to the select (and a bunch of other elements). To sum it up: 
- Better scope management in dropdown, select, dialog, tabs & date-picker, which make the numbers of watchers really go down, and avoid memory leaks
- Track by and limitTo in the select
- Reduced the number of ng-if in the select

With this, I think everyone should see a great bump in the performance.

If you can confirm it helps you, I'll be glad to hear it. I'm closing this issue, as I'm confident this problem is covered by my updates. I really wanted to do this sooner, but now it's done!
