### ISSUE TITLE
bower.json - bourbon and mdi as devDependencies

### ISSUE THREAD

**Issue by Almar** [lumapps/lumX#308]
Shouldn't bourbon and mdi be defined as devDependencies in bower.json?

If I understand correctly, lumx.css is the result of a sass compile and includes both bourbon and mdi. I'm using gulp with 'main-bower-files'. The latter finds al bower dependencies including bourbon and mdi but these are superfluous (already included in lumx.css).

**Comment by malexandre** [comment]
Hi. As you said, if you use lumx.css, those dependencies are superfluous. But most people will use lumx.scss to be able to change the theme or customize the framework. In that case, both are required. And since we give the possibility to use the sass version right in the dist, I think it's better to have those dependencies.

**Comment by Almar** [comment]
Ah, okay, bower wouldn't download them if they are marked as devDependencies. Yes, I see how that would be worse.
Thanks for your answer!
