### ISSUE TITLE
Date Picker does not work in FF 34.0.5

### ISSUE THREAD

**Issue by bitsthatmatter** [lumapps/lumX#81]
Hello,
Compliments for the project thus far. Looks already very good.

I tried to use the date picker. It works fine in Chrome and Safari but on FF when clicking inside the date field it doesn't do anything. Only when clicking on the label 'Pick a date', the date picker pops up.

**Comment by rriemann** [comment]
This seems to be the same issue like in #104 (which is newer, but has some activity).

**Comment by mgd216** [comment]
Found the same problem, also won't allow to delete the date and make the field empty/null.

Also kudos, to the project, awesome work.

**Comment by RomeroDiver** [comment]
Hi,
I am not sure if this problem is already resolved - I can still see it on the documentation page. I am looking for a datepicker for my project, and at the moment I am checking Yours. The problem with datepicker in Firefox is with disabled attribute on the input. HTML docs say that disabled element is unusable and unclickable([link](http://www.w3schools.com/tags/att_input_disabled.asp)). On the other hand, **readonly** attribute leaves input clickable - and the general functionality is similar to disabled.
I hope this helps You!

**Comment by matmkian** [comment]
I'm going to take a look on this issue next week.
Sorry for the lack of support, we're going to release a major release of LumX with a brand new documentation at the end of the month :-)

**Comment by matmkian** [comment]
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!
